repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: name-tests-test
        exclude: "tests/stubs.py"
        args: [--pytest-test-first]
      - id: no-commit-to-branch

  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: poetry run black
        types:
          - "python"

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types:
          - "python"

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types:
          - "python"
